// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Predicter is an autogenerated mock type for the Predicter type
type Predicter struct {
	mock.Mock
}

// predict provides a mock function with given fields: temp, ph, orp
func (_m *Predicter) Predict(temp string, ph string, orp string) (string, error) {
	ret := _m.Called(temp, ph, orp)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (string, error)); ok {
		return rf(temp, ph, orp)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = rf(temp, ph, orp)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(temp, ph, orp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPredicter creates a new instance of Predicter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPredicter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Predicter {
	mock := &Predicter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
