// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/swpoolcontroller/internal/ai"
)

// SampleRepo is an autogenerated mock type for the SampleRepo type
type SampleRepo struct {
	mock.Mock
}

// save provides a mock function with given fields: data
func (_m *SampleRepo) Save(data ai.SampleData) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(ai.SampleData) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSampleRepo creates a new instance of SampleRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSampleRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *SampleRepo {
	mock := &SampleRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
