run:
  deadline: 5m
linters:
  enable-all: true
  disable:
    - golint
    - varcheck
    - deadcode
    - interfacer
    - maligned
    - scopelint
    - exhaustivestruct
    - ifshort
    - structcheck
    - nosnakecase
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    - godot
    - gomnd
    - gofumpt
    - forbidigo
    - exhaustruct
    - varnamelen
    - ireturn
linters-settings:
  lll:
    line-length: 80
  wrapcheck:
    ignoreSigs:
      - .String(
      - .NoContent(
      - .Redirect(      
      - .JSON(
      - errors.Wrap( 
      - errors.New(  
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gochecknoglobals
    - path: internal/config/config_test.go
      linters:
        - paralleltest
        - tparallel
    - path: pkg/auth/jwt_test.go
      linters:
        - lll
    - path: pkg/auth/oauth2_test.go
      linters:
        - lll
