run:
  deadline: 5m
  skip-files:
    - cmd/swpc-emulator/main.go
linters:
  enable-all: true
  disable:
    - golint
    - varcheck
    - deadcode
    - interfacer
    - maligned
    - scopelint
    - exhaustivestruct
    - ifshort
    - structcheck
    - nosnakecase
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    - godot
    - gomnd
    - gofumpt
    - forbidigo
    - exhaustruct
    - varnamelen
linters-settings:
  lll:
    line-length: 120
  wrapcheck:
    ignoreSigs:
      - .String(
      - .NoContent(
      - .JSON(
      - errors.Wrap( 
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen