// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/swpoolcontroller/pkg/iot"
)

// Hub is an autogenerated mock type for the Hub type
type Hub struct {
	mock.Mock
}

// Config provides a mock function with given fields: cnf
func (_m *Hub) Config(cnf iot.DeviceConfig) {
	_m.Called(cnf)
}

// RegisterDevice provides a mock function with given fields: cnf
func (_m *Hub) RegisterDevice(d iot.Device) {
	_m.Called(d)
}

type mockConstructorTestingTNewHub interface {
	mock.TestingT
	Cleanup(func())
}

// NewHub creates a new instance of Hub. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHub(t mockConstructorTestingTNewHub) *Hub {
	mock := &Hub{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
