// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	sockets "github.com/swpoolcontroller/pkg/sockets"
)

// Hub is an autogenerated mock type for the Hub type
type Hub struct {
	mock.Mock
}

// Send provides a mock function with given fields: message
func (_m *Hub) Send(message string) {
	_m.Called(message)
}

// Status provides a mock function with given fields: resp
func (_m *Hub) Status(resp chan sockets.Status) {
	_m.Called(resp)
}

type mockConstructorTestingTNewHub interface {
	mock.TestingT
	Cleanup(func())
}

// NewHub creates a new instance of Hub. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHub(t mockConstructorTestingTNewHub) *Hub {
	mock := &Hub{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
