name: test

on:
  push:
    paths:
      - "**.go"
      - go.mod
      - go.sum
      - "**.sh"
  pull_request:
    paths:
      - "**.go"
      - go.mod
      - go.sum
      - "**.sh"

permissions:
  contents: read

jobs:

  test-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: './go.mod'
        cache: true

    - name: Test GO
      run: ./scripts/test-go.sh
